# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{whiny_attr_accessible}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott J. Tamosunas"]
  s.date = %q{2010-10-29}
  s.description = %q{Make attr_accessible and attr_protected throw exceptions in non-production mode, yo.}
  s.email = %q{tamosunas@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/mongo_mapper/accessible.rb",
     "lib/mongo_mapper/print_diffs.rb",
     "lib/mongo_mapper/protected.rb",
     "lib/util/helpers.rb",
     "lib/util/whiny_attr_accessible_error.rb",
     "lib/whiny_attr_accessible.rb",
     "spec/mongo_mapper/accessible_spec.rb",
     "spec/mongo_mapper/protected_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/scotttam/whiny_attr_accessible}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Make attr_accessible and attr_protected throw exceptions in non-production mode}
  s.test_files = [
    "spec/mongo_mapper/accessible_spec.rb",
     "spec/mongo_mapper/protected_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

